spring:
  datasource:
    url: jdbc:mysql://120.76.206.153:3306/mydatabase?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ymumwKotcoq(
    driver-class-name: com.mysql.cj.jdbc.Driver

  schedulerx2:
    endpoint: acm.aliyun.com
    namespace: 4fc55a27-a113-482c-9b22-42b4fe7119cd
    groupId: schedulerx2
    appKey: HTzibhfLlUkm9y4PwaWKUFw

mybatis-plus:
  # 指定sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/peach/api/auth/login"
        - "/api/auth/logout"
        - "/error"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"


