spring:
  datasource:
    url: jdbc:mysql://172.20.196.121:3306/mydatabase?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: ymumwKotcoq(
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 指定sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)